name: Release arm64e-upstream-next-hikari Toolchain for Intel Mac

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          repository: "Baw-Appie/llvm-project"
          ref: "arm64e-upstream-next-hikari"
          submodules: "recursive"

      - name: Setup GIT_REF
        run: |
          echo "GIT_REF=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        shell: bash
        run: |
          brew install cmake
          brew install ninja
      
      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=x86_64 -DLLVM_ENABLE_PROJECTS=clang  -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64" -DLLVM_ENABLE_ZSTD=OFF -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 -DLLVM_CREATE_XCODE_TOOLCHAIN=ON  -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_UTILS=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF -DLLVM_BUILD_TOOLS=OFF -DLLVM_INSTALL_TOOLCHAIN_ONLY=ON -DCMAKE_INSTALL_PREFIX="./install" ../llvm
          ninja
          ninja install-xcode-toolchain
          tar -czvf Hikari_LLVM19.0.0git_Intel-Mac.tar.gz ./install/Toolchains/Hikari_LLVM19.0.0git.xctoolchain
  
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Hikari_LLVM19.0.0git_Intel-Mac.tar.gz
          path: build/Hikari_LLVM19.0.0git_Intel-Mac.tar.gz
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Intel Mac - ${{ env.GIT_REF }}
          files: build/Hikari_LLVM19.0.0git_Intel-Mac.tar.gz
